# docker-compose.yml
#
version: "3.7"
services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo:4.4.2
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
